"""This module was generated by RdfCrate codegen. Do not edit by hand."""
from __future__ import annotations
from rdfcrate.rdftype import RdfClass
from rdfcrate.rdfprop import RdfProperty
from rdfcrate.rdfterm import RdfTerm
from rdfcrate.vocabs import schemaorg
from rdfcrate.vocabs import bioschemas
from rdfcrate.vocabs import bioschemas_drafts

class Labprotocol(schemaorg.Howto):
    term = RdfTerm('https://bioschemas.org/draft_terms/LabProtocol', 'Labprotocol')

class Biochemstructure(schemaorg.Biochementity):
    term = RdfTerm('https://bioschemas.org/draft_terms/BioChemStructure', 'Biochemstructure')

class Enzyme(schemaorg.Biochementity):
    term = RdfTerm('https://bioschemas.org/draft_terms/Enzyme', 'Enzyme')

class Dna(schemaorg.Biochementity):
    term = RdfTerm('https://bioschemas.org/draft_terms/DNA', 'Dna')

class Biochementity(schemaorg.Biochementity):
    term = RdfTerm('https://bioschemas.org/draft_terms/BioChemEntity', 'Biochementity')

class Study(schemaorg.Creativework):
    term = RdfTerm('https://bioschemas.org/draft_terms/Study', 'Study')

class Sequencematchingmodel(schemaorg.Creativework):
    term = RdfTerm('https://bioschemas.org/draft_terms/SequenceMatchingModel', 'Sequencematchingmodel')

class Taxonname(schemaorg.Creativework):
    term = RdfTerm('https://bioschemas.org/draft_terms/TaxonName', 'Taxonname')

class Rna(bioschemas.Biochementity):
    term = RdfTerm('https://bioschemas.org/draft_terms/RNA', 'Rna')

class Sequenceannotation(bioschemas.Biochementity):
    term = RdfTerm('https://bioschemas.org/draft_terms/SequenceAnnotation', 'Sequenceannotation')

class Sequencerange(bioschemas.Biochementity):
    term = RdfTerm('https://bioschemas.org/draft_terms/SequenceRange', 'Sequencerange')

class Taxon(schemaorg.Thing):
    term = RdfTerm('https://bioschemas.org/draft_terms/Taxon', 'Taxon')

class Phenotype(schemaorg.Thing):
    term = RdfTerm('https://bioschemas.org/draft_terms/Phenotype', 'Phenotype')

class Sample(schemaorg.Thing):
    term = RdfTerm('https://bioschemas.org/draft_terms/Sample', 'Sample')

class Gene(Biochementity):
    term = RdfTerm('https://bioschemas.org/draft_terms/Gene', 'Gene')

class Protein(Biochementity):
    term = RdfTerm('https://bioschemas.org/draft_terms/Protein', 'Protein')

class reagent(RdfProperty[schemaorg.Text | schemaorg.Url | schemaorg.Biochementity | schemaorg.Molecularentity | schemaorg.Chemicalsubstance | schemaorg.Definedterm | schemaorg.Propertyvalue]):
    term = RdfTerm('https://bioschemas.org/draft_terms/reagent', 'reagent')

class labequipment(RdfProperty[schemaorg.Definedterm | schemaorg.Propertyvalue | schemaorg.Text | schemaorg.Url]):
    term = RdfTerm('https://bioschemas.org/draft_terms/labEquipment', 'labequipment')

class scientificname(RdfProperty[bioschemas_drafts.Taxonname | schemaorg.Text | schemaorg.Url]):
    term = RdfTerm('https://bioschemas.org/draft_terms/scientificName', 'scientificname')

class taxonomicrange(RdfProperty[schemaorg.Text | schemaorg.Url | schemaorg.Taxon | schemaorg.Definedterm]):
    term = RdfTerm('https://bioschemas.org/draft_terms/taxonomicRange', 'taxonomicrange')

class hasassociatedbiochementity(RdfProperty[bioschemas_drafts.Rna | schemaorg.Protein]):
    term = RdfTerm('https://bioschemas.org/draft_terms/hasAssociatedBioChemEntity', 'hasassociatedbiochementity')

class studyprocess(RdfProperty[schemaorg.Url | schemaorg.Text | schemaorg.Propertyvalue]):
    term = RdfTerm('https://bioschemas.org/draft_terms/studyProcess', 'studyprocess')

class protocoladvantage(RdfProperty[schemaorg.Creativework | schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/protocolAdvantage', 'protocoladvantage')

class optimaltemperature(RdfProperty[schemaorg.Quantity]):
    term = RdfTerm('https://bioschemas.org/draft_terms/optimalTemperature', 'optimaltemperature')

class hasstatus(RdfProperty[schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/hasStatus', 'hasstatus')

class protocoloutcome(RdfProperty[schemaorg.Creativework | schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/protocolOutcome', 'protocoloutcome')

class intendeduse(RdfProperty[schemaorg.Definedterm | schemaorg.Url | schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/intendedUse', 'intendeduse')

class anatomicallocation(RdfProperty[schemaorg.Definedterm | schemaorg.Url | schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/anatomicalLocation', 'anatomicallocation')

class biosample(RdfProperty[schemaorg.Definedterm | schemaorg.Propertyvalue | bioschemas.Biosample | schemaorg.Text | schemaorg.Url | schemaorg.Biochementity | schemaorg.Taxon]):
    term = RdfTerm('https://bioschemas.org/draft_terms/bioSample', 'biosample')

class studylocation(RdfProperty[schemaorg.Administrativearea | schemaorg.Place]):
    term = RdfTerm('https://bioschemas.org/draft_terms/studyLocation', 'studylocation')

class iscodingrna(RdfProperty[schemaorg.Boolean]):
    term = RdfTerm('https://bioschemas.org/draft_terms/isCodingRNA', 'iscodingrna')

class haskineticrate(RdfProperty[schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/hasKineticRate', 'haskineticrate')

class hassequence(RdfProperty[schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/hasSequence', 'hassequence')

class studysubject(RdfProperty[schemaorg.Medicalentity | schemaorg.Biochementity]):
    term = RdfTerm('https://bioschemas.org/draft_terms/studySubject', 'studysubject')

class protocolapplication(RdfProperty[schemaorg.Text | schemaorg.Creativework]):
    term = RdfTerm('https://bioschemas.org/draft_terms/protocolApplication', 'protocolapplication')

class startdate(RdfProperty[schemaorg.Datetime | schemaorg.Date]):
    term = RdfTerm('https://bioschemas.org/draft_terms/startDate', 'startdate')

class hassequenceannotation(RdfProperty[schemaorg.Url | bioschemas_drafts.Sequenceannotation]):
    term = RdfTerm('https://bioschemas.org/draft_terms/hasSequenceAnnotation', 'hassequenceannotation')

class islocatedinsubcellularlocation(RdfProperty[schemaorg.Url | schemaorg.Definedterm | schemaorg.Propertyvalue]):
    term = RdfTerm('https://bioschemas.org/draft_terms/isLocatedInSubcellularLocation', 'islocatedinsubcellularlocation')

class expressedin(RdfProperty[schemaorg.Biochementity | schemaorg.Definedterm | schemaorg.Anatomicalsystem | schemaorg.Anatomicalstructure]):
    term = RdfTerm('https://bioschemas.org/draft_terms/expressedIn', 'expressedin')

class protocollimitation(RdfProperty[schemaorg.Creativework | schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/protocolLimitation', 'protocollimitation')

class hascofactor(RdfProperty[schemaorg.Chemicalsubstance]):
    term = RdfTerm('https://bioschemas.org/draft_terms/hasCofactor', 'hascofactor')

class additionalproperty(RdfProperty[schemaorg.Propertyvalue]):
    term = RdfTerm('https://bioschemas.org/draft_terms/additionalProperty', 'additionalproperty')

class alternativeof(RdfProperty[schemaorg.Gene]):
    term = RdfTerm('https://bioschemas.org/draft_terms/alternativeOf', 'alternativeof')

class isinvolvedinbiologicalprocess(RdfProperty[schemaorg.Definedterm | schemaorg.Propertyvalue | schemaorg.Url]):
    term = RdfTerm('https://bioschemas.org/draft_terms/isInvolvedInBiologicalProcess', 'isinvolvedinbiologicalprocess')

class creationmethod(RdfProperty[schemaorg.Propertyvalue | schemaorg.Url | schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/creationMethod', 'creationmethod')

class match(RdfProperty[schemaorg.Biochementity]):
    term = RdfTerm('https://bioschemas.org/draft_terms/match', 'match')

class startuncertainty(RdfProperty[schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/startUncertainty', 'startuncertainty')

class childtaxon(RdfProperty[schemaorg.Text | schemaorg.Url | schemaorg.Taxon]):
    term = RdfTerm('https://bioschemas.org/draft_terms/childTaxon', 'childtaxon')

class sequencevalue(RdfProperty[schemaorg.Text | schemaorg.Url]):
    term = RdfTerm('https://bioschemas.org/draft_terms/sequenceValue', 'sequencevalue')

class massresolution(RdfProperty[schemaorg.Quantity]):
    term = RdfTerm('https://bioschemas.org/draft_terms/massResolution', 'massresolution')

class rangestart(RdfProperty[schemaorg.Integer]):
    term = RdfTerm('https://bioschemas.org/draft_terms/rangeStart', 'rangestart')

class ismatchedby(RdfProperty[bioschemas_drafts.Sequencematchingmodel]):
    term = RdfTerm('https://bioschemas.org/draft_terms/isMatchedBy', 'ismatchedby')

class associateddisease(RdfProperty[schemaorg.Url | schemaorg.Propertyvalue | schemaorg.Medicalcondition]):
    term = RdfTerm('https://bioschemas.org/draft_terms/associatedDisease', 'associateddisease')

class biologicaltype(RdfProperty[schemaorg.Url | schemaorg.Biochementity | schemaorg.Text | schemaorg.Definedterm]):
    term = RdfTerm('https://bioschemas.org/draft_terms/biologicalType', 'biologicaltype')

class encodesbiochementity(RdfProperty[bioschemas.Biochementity]):
    term = RdfTerm('https://bioschemas.org/draft_terms/encodesBioChemEntity', 'encodesbiochementity')

class ethicallegalsocial(RdfProperty[schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/ethicalLegalSocial', 'ethicallegalsocial')

class modelsignature(RdfProperty[schemaorg.Propertyvalue | schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/modelSignature', 'modelsignature')

class taxonrank(RdfProperty[schemaorg.Text | schemaorg.Url | schemaorg.Propertyvalue]):
    term = RdfTerm('https://bioschemas.org/draft_terms/taxonRank', 'taxonrank')

class hasmolecularfunction(RdfProperty[schemaorg.Definedterm | schemaorg.Propertyvalue | schemaorg.Url]):
    term = RdfTerm('https://bioschemas.org/draft_terms/hasMolecularFunction', 'hasmolecularfunction')

class modeldataset(RdfProperty[schemaorg.Dataset]):
    term = RdfTerm('https://bioschemas.org/draft_terms/modelDataset', 'modeldataset')

class studydomain(RdfProperty[schemaorg.Propertyvalue | schemaorg.Text | schemaorg.Url]):
    term = RdfTerm('https://bioschemas.org/draft_terms/studyDomain', 'studydomain')

class optimalph(RdfProperty[schemaorg.Number]):
    term = RdfTerm('https://bioschemas.org/draft_terms/optimalPH', 'optimalph')

class computationaltool(RdfProperty[schemaorg.Definedterm | schemaorg.Propertyvalue | bioschemas.Computationalworkflow | schemaorg.Softwaresourcecode | schemaorg.Softwareapplication]):
    term = RdfTerm('https://bioschemas.org/draft_terms/computationalTool', 'computationaltool')

class valuereference(RdfProperty[schemaorg.Structuredvalue | schemaorg.Propertyvalue | schemaorg.Quantitativevalue | schemaorg.Enumeration | schemaorg.Qualitativevalue | schemaorg.Text | schemaorg.Url | schemaorg.Definedterm]):
    term = RdfTerm('https://bioschemas.org/draft_terms/valueReference', 'valuereference')

class sample(RdfProperty[schemaorg.Thing | schemaorg.Definedterm | schemaorg.Propertyvalue]):
    term = RdfTerm('https://bioschemas.org/draft_terms/sample', 'sample')

class enddate(RdfProperty[schemaorg.Datetime | schemaorg.Date]):
    term = RdfTerm('https://bioschemas.org/draft_terms/endDate', 'enddate')

class alternatescientificname(RdfProperty[bioschemas_drafts.Taxonname | schemaorg.Text | schemaorg.Url]):
    term = RdfTerm('https://bioschemas.org/draft_terms/alternateScientificName', 'alternatescientificname')

class rangeend(RdfProperty[schemaorg.Integer]):
    term = RdfTerm('https://bioschemas.org/draft_terms/rangeEnd', 'rangeend')

class hascoenzyme(RdfProperty[schemaorg.Biochementity]):
    term = RdfTerm('https://bioschemas.org/draft_terms/hasCoenzyme', 'hascoenzyme')

class sequenceorientation(RdfProperty[schemaorg.Integer]):
    term = RdfTerm('https://bioschemas.org/draft_terms/sequenceOrientation', 'sequenceorientation')

class relatedstudy(RdfProperty[bioschemas_drafts.Study]):
    term = RdfTerm('https://bioschemas.org/draft_terms/relatedStudy', 'relatedstudy')

class hasbiopolymersequence(RdfProperty[schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/hasBioPolymerSequence', 'hasbiopolymersequence')

class sequencelocation(RdfProperty[bioschemas_drafts.Sequencerange]):
    term = RdfTerm('https://bioschemas.org/draft_terms/sequenceLocation', 'sequencelocation')

class boundmolecule(RdfProperty[schemaorg.Molecularentity | schemaorg.Url | schemaorg.Biochementity | schemaorg.Chemicalsubstance | schemaorg.Definedterm]):
    term = RdfTerm('https://bioschemas.org/draft_terms/boundMolecule', 'boundmolecule')

class biochemassociation(RdfProperty[schemaorg.Biochementity]):
    term = RdfTerm('https://bioschemas.org/draft_terms/bioChemAssociation', 'biochemassociation')

class enduncertainty(RdfProperty[schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/endUncertainty', 'enduncertainty')

class parenttaxon(RdfProperty[schemaorg.Url | schemaorg.Taxon | schemaorg.Text]):
    term = RdfTerm('https://bioschemas.org/draft_terms/parentTaxon', 'parenttaxon')