"""This module was generated by RdfCrate codegen. Do not edit by hand."""
from __future__ import annotations
from rdfcrate.rdftype import RdfClass
from rdfcrate.rdfprop import RdfProperty
from rdfcrate.rdfterm import RdfTerm
from rdfcrate.vocabs import rdfs
from rdfcrate.vocabs import rdf
from rdfcrate.rdftype import RdfType
from rdfcrate.vocabs import owl

class Datarange(rdfs.Datatype):
    term = RdfTerm('http://www.w3.org/2002/07/owl#DataRange', 'Datarange')

class Class(rdfs.Class):
    term = RdfTerm('http://www.w3.org/2002/07/owl#Class', 'Class')

class Deprecatedclass(rdfs.Class):
    term = RdfTerm('http://www.w3.org/2002/07/owl#DeprecatedClass', 'Deprecatedclass')

class Annotationproperty(rdf.Property):
    term = RdfTerm('http://www.w3.org/2002/07/owl#AnnotationProperty', 'Annotationproperty')

class Datatypeproperty(rdf.Property):
    term = RdfTerm('http://www.w3.org/2002/07/owl#DatatypeProperty', 'Datatypeproperty')

class Deprecatedproperty(rdf.Property):
    term = RdfTerm('http://www.w3.org/2002/07/owl#DeprecatedProperty', 'Deprecatedproperty')

class Functionalproperty(rdf.Property):
    term = RdfTerm('http://www.w3.org/2002/07/owl#FunctionalProperty', 'Functionalproperty')

class Objectproperty(rdf.Property):
    term = RdfTerm('http://www.w3.org/2002/07/owl#ObjectProperty', 'Objectproperty')

class Ontologyproperty(rdf.Property):
    term = RdfTerm('http://www.w3.org/2002/07/owl#OntologyProperty', 'Ontologyproperty')

class Alldifferent(rdfs.Resource):
    term = RdfTerm('http://www.w3.org/2002/07/owl#AllDifferent', 'Alldifferent')

class Alldisjointclasses(rdfs.Resource):
    term = RdfTerm('http://www.w3.org/2002/07/owl#AllDisjointClasses', 'Alldisjointclasses')

class Alldisjointproperties(rdfs.Resource):
    term = RdfTerm('http://www.w3.org/2002/07/owl#AllDisjointProperties', 'Alldisjointproperties')

class Annotation(rdfs.Resource):
    term = RdfTerm('http://www.w3.org/2002/07/owl#Annotation', 'Annotation')

class Axiom(rdfs.Resource):
    term = RdfTerm('http://www.w3.org/2002/07/owl#Axiom', 'Axiom')

class Negativepropertyassertion(rdfs.Resource):
    term = RdfTerm('http://www.w3.org/2002/07/owl#NegativePropertyAssertion', 'Negativepropertyassertion')

class Ontology(rdfs.Resource):
    term = RdfTerm('http://www.w3.org/2002/07/owl#Ontology', 'Ontology')

class Thing(RdfClass):
    term = RdfTerm('http://www.w3.org/2002/07/owl#Thing', 'Thing')

class Restriction(Class):
    term = RdfTerm('http://www.w3.org/2002/07/owl#Restriction', 'Restriction')

class Asymmetricproperty(Objectproperty):
    term = RdfTerm('http://www.w3.org/2002/07/owl#AsymmetricProperty', 'Asymmetricproperty')

class Inversefunctionalproperty(Objectproperty):
    term = RdfTerm('http://www.w3.org/2002/07/owl#InverseFunctionalProperty', 'Inversefunctionalproperty')

class Irreflexiveproperty(Objectproperty):
    term = RdfTerm('http://www.w3.org/2002/07/owl#IrreflexiveProperty', 'Irreflexiveproperty')

class Reflexiveproperty(Objectproperty):
    term = RdfTerm('http://www.w3.org/2002/07/owl#ReflexiveProperty', 'Reflexiveproperty')

class Symmetricproperty(Objectproperty):
    term = RdfTerm('http://www.w3.org/2002/07/owl#SymmetricProperty', 'Symmetricproperty')

class Transitiveproperty(Objectproperty):
    term = RdfTerm('http://www.w3.org/2002/07/owl#TransitiveProperty', 'Transitiveproperty')

class Namedindividual(Thing):
    term = RdfTerm('http://www.w3.org/2002/07/owl#NamedIndividual', 'Namedindividual')

class Nothing(Thing):
    term = RdfTerm('http://www.w3.org/2002/07/owl#Nothing', 'Nothing')

class allvaluesfrom(RdfProperty[rdfs.Class]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#allValuesFrom', 'allvaluesfrom')

class annotatedproperty(RdfProperty[rdfs.Resource]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#annotatedProperty', 'annotatedproperty')

class annotatedsource(RdfProperty[rdfs.Resource]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#annotatedSource', 'annotatedsource')

class annotatedtarget(RdfProperty[rdfs.Resource]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#annotatedTarget', 'annotatedtarget')

class assertionproperty(RdfProperty[rdf.Property]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#assertionProperty', 'assertionproperty')

class cardinality(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#cardinality', 'cardinality')

class complementof(RdfProperty[owl.Class]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#complementOf', 'complementof')

class datatypecomplementof(RdfProperty[rdfs.Datatype]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#datatypeComplementOf', 'datatypecomplementof')

class differentfrom(RdfProperty[owl.Thing]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#differentFrom', 'differentfrom')

class disjointunionof(RdfProperty[rdf.List]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#disjointUnionOf', 'disjointunionof')

class disjointwith(RdfProperty[owl.Class]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#disjointWith', 'disjointwith')

class distinctmembers(RdfProperty[rdf.List]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#distinctMembers', 'distinctmembers')

class equivalentclass(RdfProperty[rdfs.Class]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#equivalentClass', 'equivalentclass')

class equivalentproperty(RdfProperty[rdf.Property]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#equivalentProperty', 'equivalentproperty')

class haskey(RdfProperty[rdf.List]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#hasKey', 'haskey')

class hasself(RdfProperty[rdfs.Resource]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#hasSelf', 'hasself')

class hasvalue(RdfProperty[rdfs.Resource]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#hasValue', 'hasvalue')

class intersectionof(RdfProperty[rdf.List]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#intersectionOf', 'intersectionof')

class inverseof(RdfProperty[owl.Objectproperty]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#inverseOf', 'inverseof')

class maxcardinality(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#maxCardinality', 'maxcardinality')

class maxqualifiedcardinality(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#maxQualifiedCardinality', 'maxqualifiedcardinality')

class members(RdfProperty[rdf.List]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#members', 'members')

class mincardinality(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#minCardinality', 'mincardinality')

class minqualifiedcardinality(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#minQualifiedCardinality', 'minqualifiedcardinality')

class onclass(RdfProperty[owl.Class]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#onClass', 'onclass')

class ondatarange(RdfProperty[rdfs.Datatype]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#onDataRange', 'ondatarange')

class ondatatype(RdfProperty[rdfs.Datatype]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#onDatatype', 'ondatatype')

class oneof(RdfProperty[rdf.List]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#oneOf', 'oneof')

class onproperties(RdfProperty[rdf.List]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#onProperties', 'onproperties')

class onproperty(RdfProperty[rdf.Property]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#onProperty', 'onproperty')

class propertychainaxiom(RdfProperty[rdf.List]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#propertyChainAxiom', 'propertychainaxiom')

class propertydisjointwith(RdfProperty[rdf.Property]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#propertyDisjointWith', 'propertydisjointwith')

class qualifiedcardinality(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#qualifiedCardinality', 'qualifiedcardinality')

class sameas(RdfProperty[owl.Thing]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#sameAs', 'sameas')

class somevaluesfrom(RdfProperty[rdfs.Class]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#someValuesFrom', 'somevaluesfrom')

class sourceindividual(RdfProperty[owl.Thing]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#sourceIndividual', 'sourceindividual')

class targetindividual(RdfProperty[owl.Thing]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#targetIndividual', 'targetindividual')

class targetvalue(RdfProperty[rdfs.Literal]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#targetValue', 'targetvalue')

class unionof(RdfProperty[rdf.List]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#unionOf', 'unionof')

class withrestrictions(RdfProperty[rdf.List]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#withRestrictions', 'withrestrictions')

class backwardcompatiblewith(RdfProperty[owl.Ontology]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#backwardCompatibleWith', 'backwardcompatiblewith')

class deprecated(RdfProperty[rdfs.Resource]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#deprecated', 'deprecated')

class incompatiblewith(RdfProperty[owl.Ontology]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#incompatibleWith', 'incompatiblewith')

class priorversion(RdfProperty[owl.Ontology]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#priorVersion', 'priorversion')

class versioninfo(RdfProperty[rdfs.Resource]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#versionInfo', 'versioninfo')

class bottomdataproperty(RdfProperty[rdfs.Literal]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#bottomDataProperty', 'bottomdataproperty')

class topdataproperty(RdfProperty[rdfs.Literal]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#topDataProperty', 'topdataproperty')

class bottomobjectproperty(RdfProperty[owl.Thing]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#bottomObjectProperty', 'bottomobjectproperty')

class topobjectproperty(RdfProperty[owl.Thing]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#topObjectProperty', 'topobjectproperty')

class imports(RdfProperty[owl.Ontology]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#imports', 'imports')

class versioniri(RdfProperty[owl.Ontology]):
    term = RdfTerm('http://www.w3.org/2002/07/owl#versionIRI', 'versioniri')