"""This module was generated by RdfCrate codegen. Do not edit by hand."""
from __future__ import annotations
from rdfcrate.rdftype import RdfClass
from rdfcrate.rdfprop import RdfProperty
from rdfcrate.rdfterm import RdfTerm
from rdfcrate.vocabs import owl
from rdfcrate.rdftype import RdfType
from rdfcrate.vocabs import prov
from rdfcrate.vocabs import rdfs

class Agent(RdfClass):
    term = RdfTerm('http://www.w3.org/ns/prov#Agent', 'Agent')

class Activity(RdfClass):
    term = RdfTerm('http://www.w3.org/ns/prov#Activity', 'Activity')

class Influence(RdfClass):
    term = RdfTerm('http://www.w3.org/ns/prov#Influence', 'Influence')

class Instantaneousevent(RdfClass):
    term = RdfTerm('http://www.w3.org/ns/prov#InstantaneousEvent', 'Instantaneousevent')

class Entity(RdfClass):
    term = RdfTerm('http://www.w3.org/ns/prov#Entity', 'Entity')

class Dictionary(RdfClass):
    term = RdfTerm('http://www.w3.org/ns/prov#Dictionary', 'Dictionary')

class Location(RdfClass):
    term = RdfTerm('http://www.w3.org/ns/prov#Location', 'Location')

class Role(RdfClass):
    term = RdfTerm('http://www.w3.org/ns/prov#Role', 'Role')

class KeyEntityPair(RdfClass):
    term = RdfTerm('http://www.w3.org/ns/prov#KeyEntityPair', 'KeyEntityPair')

class Softwareagent(Agent, owl.Thing):
    term = RdfTerm('http://www.w3.org/ns/prov#SoftwareAgent', 'Softwareagent')

class Organization(Agent):
    term = RdfTerm('http://www.w3.org/ns/prov#Organization', 'Organization')

class Person(Agent):
    term = RdfTerm('http://www.w3.org/ns/prov#Person', 'Person')

class Accept(Activity):
    term = RdfTerm('http://www.w3.org/ns/prov#Accept', 'Accept')

class Contribute(Activity):
    term = RdfTerm('http://www.w3.org/ns/prov#Contribute', 'Contribute')

class Copyright(Activity):
    term = RdfTerm('http://www.w3.org/ns/prov#Copyright', 'Copyright')

class Modify(Activity):
    term = RdfTerm('http://www.w3.org/ns/prov#Modify', 'Modify')

class Publish(Activity):
    term = RdfTerm('http://www.w3.org/ns/prov#Publish', 'Publish')

class Replace(Activity):
    term = RdfTerm('http://www.w3.org/ns/prov#Replace', 'Replace')

class Rightsassignment(Activity):
    term = RdfTerm('http://www.w3.org/ns/prov#RightsAssignment', 'Rightsassignment')

class Submit(Activity):
    term = RdfTerm('http://www.w3.org/ns/prov#Submit', 'Submit')

class Activityinfluence(Influence):
    term = RdfTerm('http://www.w3.org/ns/prov#ActivityInfluence', 'Activityinfluence')

class Agentinfluence(Influence):
    term = RdfTerm('http://www.w3.org/ns/prov#AgentInfluence', 'Agentinfluence')

class Entityinfluence(Influence):
    term = RdfTerm('http://www.w3.org/ns/prov#EntityInfluence', 'Entityinfluence')

class Bundle(Entity):
    term = RdfTerm('http://www.w3.org/ns/prov#Bundle', 'Bundle')

class Collection(Entity):
    term = RdfTerm('http://www.w3.org/ns/prov#Collection', 'Collection')

class Plan(Entity):
    term = RdfTerm('http://www.w3.org/ns/prov#Plan', 'Plan')

class Contributor(Role):
    term = RdfTerm('http://www.w3.org/ns/prov#Contributor', 'Contributor')

class Publisher(Role):
    term = RdfTerm('http://www.w3.org/ns/prov#Publisher', 'Publisher')

class Rightsholder(Role):
    term = RdfTerm('http://www.w3.org/ns/prov#RightsHolder', 'Rightsholder')

class Servicedescription(Softwareagent):
    term = RdfTerm('http://www.w3.org/ns/prov#ServiceDescription', 'Servicedescription')

class Provenanceservice(Softwareagent):
    term = RdfTerm('http://www.w3.org/ns/prov#DirectQueryService', 'Provenanceservice')

class Create(Contribute):
    term = RdfTerm('http://www.w3.org/ns/prov#Create', 'Create')

class Communication(Activityinfluence):
    term = RdfTerm('http://www.w3.org/ns/prov#Communication', 'Communication')

class Generation(Activityinfluence, Instantaneousevent):
    term = RdfTerm('http://www.w3.org/ns/prov#Generation', 'Generation')

class Invalidation(Activityinfluence, Instantaneousevent):
    term = RdfTerm('http://www.w3.org/ns/prov#Invalidation', 'Invalidation')

class Association(Agentinfluence):
    term = RdfTerm('http://www.w3.org/ns/prov#Association', 'Association')

class Attribution(Agentinfluence):
    term = RdfTerm('http://www.w3.org/ns/prov#Attribution', 'Attribution')

class Delegation(Agentinfluence):
    term = RdfTerm('http://www.w3.org/ns/prov#Delegation', 'Delegation')

class Derivation(Entityinfluence):
    term = RdfTerm('http://www.w3.org/ns/prov#Derivation', 'Derivation')

class End(Entityinfluence, Instantaneousevent):
    term = RdfTerm('http://www.w3.org/ns/prov#End', 'End')

class Start(Entityinfluence, Instantaneousevent):
    term = RdfTerm('http://www.w3.org/ns/prov#Start', 'Start')

class Usage(Entityinfluence, Instantaneousevent):
    term = RdfTerm('http://www.w3.org/ns/prov#Usage', 'Usage')

class Emptycollection(Collection):
    term = RdfTerm('http://www.w3.org/ns/prov#EmptyCollection', 'Emptycollection')

class Creator(Contributor):
    term = RdfTerm('http://www.w3.org/ns/prov#Creator', 'Creator')

class Primarysource(Derivation):
    term = RdfTerm('http://www.w3.org/ns/prov#PrimarySource', 'Primarysource')

class Quotation(Derivation):
    term = RdfTerm('http://www.w3.org/ns/prov#Quotation', 'Quotation')

class Revision(Derivation):
    term = RdfTerm('http://www.w3.org/ns/prov#Revision', 'Revision')

class Insertion(Derivation):
    term = RdfTerm('http://www.w3.org/ns/prov#Insertion', 'Insertion')

class Removal(Derivation):
    term = RdfTerm('http://www.w3.org/ns/prov#Removal', 'Removal')

class EmptyDictionary(Emptycollection, Dictionary):
    term = RdfTerm('http://www.w3.org/ns/prov#EmptyDictionary', 'EmptyDictionary')

class aq(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#aq', 'aq')

class category(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#category', 'category')

class component(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#component', 'component')

class constraints(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#constraints', 'constraints')

class definition(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#definition', 'definition')

class dm(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#dm', 'dm')

class editorialNote(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#editorialNote', 'editorialNote')

class editorsDefinition(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#editorsDefinition', 'editorsDefinition')

class inverse(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#inverse', 'inverse')

class n(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#n', 'n')

class order(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#order', 'order')

class qualifiedForm(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedForm', 'qualifiedForm')

class sharesDefinitionWith(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#sharesDefinitionWith', 'sharesDefinitionWith')

class specializationof(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#specializationOf', 'specializationof')

class todo(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#todo', 'todo')

class unqualifiedForm(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#unqualifiedForm', 'unqualifiedForm')

class wasrevisionof(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#wasRevisionOf', 'wasrevisionof')

class attime(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#atTime', 'attime')

class endedattime(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#endedAtTime', 'endedattime')

class generatedattime(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#generatedAtTime', 'generatedattime')

class invalidatedattime(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#invalidatedAtTime', 'invalidatedattime')

class startedattime(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#startedAtTime', 'startedattime')

class value(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#value', 'value')

class provenanceuritemplate(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#provenanceUriTemplate', 'provenanceuritemplate')

class pairkey(RdfProperty[rdfs.Literal]):
    term = RdfTerm('http://www.w3.org/ns/prov#pairKey', 'pairkey')

class removedkey(RdfProperty[rdfs.Literal]):
    term = RdfTerm('http://www.w3.org/ns/prov#removedKey', 'removedkey')

class pairkey(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#pairEntity', 'pairkey')

class actedonbehalfof(RdfProperty[prov.Agent]):
    term = RdfTerm('http://www.w3.org/ns/prov#actedOnBehalfOf', 'actedonbehalfof')

class activity(RdfProperty[prov.Activity]):
    term = RdfTerm('http://www.w3.org/ns/prov#activity', 'activity')

class agent(RdfProperty[prov.Agent]):
    term = RdfTerm('http://www.w3.org/ns/prov#agent', 'agent')

class alternateof(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#alternateOf', 'alternateof')

class atlocation(RdfProperty[prov.Location]):
    term = RdfTerm('http://www.w3.org/ns/prov#atLocation', 'atlocation')

class entity(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#entity', 'entity')

class generated(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#generated', 'generated')

class hadactivity(RdfProperty[prov.Activity]):
    term = RdfTerm('http://www.w3.org/ns/prov#hadActivity', 'hadactivity')

class hadgeneration(RdfProperty[prov.Generation]):
    term = RdfTerm('http://www.w3.org/ns/prov#hadGeneration', 'hadgeneration')

class hadmember(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#hadMember', 'hadmember')

class hadplan(RdfProperty[prov.Plan]):
    term = RdfTerm('http://www.w3.org/ns/prov#hadPlan', 'hadplan')

class hadprimarysource(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#hadPrimarySource', 'hadprimarysource')

class hadrole(RdfProperty[prov.Role]):
    term = RdfTerm('http://www.w3.org/ns/prov#hadRole', 'hadrole')

class hadusage(RdfProperty[prov.Usage]):
    term = RdfTerm('http://www.w3.org/ns/prov#hadUsage', 'hadusage')

class influenced(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#influenced', 'influenced')

class influencer(RdfProperty[owl.Thing]):
    term = RdfTerm('http://www.w3.org/ns/prov#influencer', 'influencer')

class invalidated(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#invalidated', 'invalidated')

class qualifiedassociation(RdfProperty[prov.Association]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedAssociation', 'qualifiedassociation')

class qualifiedattribution(RdfProperty[prov.Attribution]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedAttribution', 'qualifiedattribution')

class qualifiedcommunication(RdfProperty[prov.Communication]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedCommunication', 'qualifiedcommunication')

class qualifieddelegation(RdfProperty[prov.Delegation]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedDelegation', 'qualifieddelegation')

class qualifiedderivation(RdfProperty[prov.Derivation]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedDerivation', 'qualifiedderivation')

class qualifiedend(RdfProperty[prov.End]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedEnd', 'qualifiedend')

class qualifiedgeneration(RdfProperty[prov.Generation]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedGeneration', 'qualifiedgeneration')

class qualifiedinfluence(RdfProperty[prov.Influence]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedInfluence', 'qualifiedinfluence')

class qualifiedinvalidation(RdfProperty[prov.Invalidation]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedInvalidation', 'qualifiedinvalidation')

class qualifiedprimarysource(RdfProperty[prov.Primarysource]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedPrimarySource', 'qualifiedprimarysource')

class qualifiedquotation(RdfProperty[prov.Quotation]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedQuotation', 'qualifiedquotation')

class qualifiedrevision(RdfProperty[prov.Revision]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedRevision', 'qualifiedrevision')

class qualifiedstart(RdfProperty[prov.Start]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedStart', 'qualifiedstart')

class qualifiedusage(RdfProperty[prov.Usage]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedUsage', 'qualifiedusage')

class used(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#used', 'used')

class wasassociatedwith(RdfProperty[prov.Agent]):
    term = RdfTerm('http://www.w3.org/ns/prov#wasAssociatedWith', 'wasassociatedwith')

class wasattributedto(RdfProperty[prov.Agent]):
    term = RdfTerm('http://www.w3.org/ns/prov#wasAttributedTo', 'wasattributedto')

class wasderivedfrom(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#wasDerivedFrom', 'wasderivedfrom')

class wasendedby(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#wasEndedBy', 'wasendedby')

class wasgeneratedby(RdfProperty[prov.Activity]):
    term = RdfTerm('http://www.w3.org/ns/prov#wasGeneratedBy', 'wasgeneratedby')

class wasinfluencedby(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#wasInfluencedBy', 'wasinfluencedby')

class wasinformedby(RdfProperty[prov.Activity]):
    term = RdfTerm('http://www.w3.org/ns/prov#wasInformedBy', 'wasinformedby')

class wasinvalidatedby(RdfProperty[prov.Activity]):
    term = RdfTerm('http://www.w3.org/ns/prov#wasInvalidatedBy', 'wasinvalidatedby')

class wasquotedfrom(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#wasQuotedFrom', 'wasquotedfrom')

class wasstartedby(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#wasStartedBy', 'wasstartedby')

class hasAnchor(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#has_anchor', 'hasAnchor')

class hasProvenance(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#has_provenance', 'hasProvenance')

class hasprovenanceservice(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#has_query_service', 'hasprovenanceservice')

class describesservice(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#describesService', 'describesservice')

class provenancePingback(RdfProperty[RdfType]):
    term = RdfTerm('http://www.w3.org/ns/prov#pingback', 'provenancePingback')

class dictionary(RdfProperty[prov.Dictionary]):
    term = RdfTerm('http://www.w3.org/ns/prov#dictionary', 'dictionary')

class derivedbyinsertionfrom(RdfProperty[prov.Dictionary]):
    term = RdfTerm('http://www.w3.org/ns/prov#derivedByInsertionFrom', 'derivedbyinsertionfrom')

class derivedbyremovalfrom(RdfProperty[prov.Dictionary]):
    term = RdfTerm('http://www.w3.org/ns/prov#derivedByRemovalFrom', 'derivedbyremovalfrom')

class insertedkeyentitypair(RdfProperty[prov.KeyEntityPair]):
    term = RdfTerm('http://www.w3.org/ns/prov#insertedKeyEntityPair', 'insertedkeyentitypair')

class haddictionarymember(RdfProperty[prov.KeyEntityPair]):
    term = RdfTerm('http://www.w3.org/ns/prov#hadDictionaryMember', 'haddictionarymember')

class qualifiedinsertion(RdfProperty[prov.Insertion]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedInsertion', 'qualifiedinsertion')

class qualifiedremoval(RdfProperty[prov.Removal]):
    term = RdfTerm('http://www.w3.org/ns/prov#qualifiedRemoval', 'qualifiedremoval')

class asinbundle(RdfProperty[prov.Bundle]):
    term = RdfTerm('http://www.w3.org/ns/prov#asInBundle', 'asinbundle')

class mentionof(RdfProperty[prov.Entity]):
    term = RdfTerm('http://www.w3.org/ns/prov#mentionOf', 'mentionof')